name: CI

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Build & Test
        uses: actions/checkout@v2.1.0
      - run: echo ${{ github.ref }}
      # - run: npm ci
      # - run: npm test
      
        if: ${{ github.ref == 'refs/tags/' }}
          echo "it is tag"
      - name: NPM Publish
        uses: actions/checkout@v2.1.0
      - run: echo "test"
      # - name: NPM Publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}