name: CI

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Build & Test
        uses: actions/checkout@v2.1.0
      - run: npm ci
      - run: npm test

      # - name: NPM Publish
      #   # You may pin to the exact commit or the version.
      #   # uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
      #   uses: JS-DevTools/npm-publish@v1