name: CI

on: [push]

jobs:
  build:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12
          - 14
          - 16

    steps:
      - name: Build & Test
        uses: actions/checkout@v2.1.0
      # Temporarily disabled until problem with type:module has been resolved
      # - run: npm audit --audit-level=moderate
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm run e2e